# Permalinks
permalink:           pretty

# Setup
title:               Huzeifa Naim
tagline:             Personal website
url:                 http://huzeifanaim.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Jekyll-archives config.
jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: 'archives/:year/'
    month: 'archives/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
 
# About/contact
author:
  name:              Huzeifa Naim
  url:               https://twitter.com/huzi94
  email:             huzeifanaim@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/huzeifa/huzeifa.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives
