# Site settings
title: Huzeifa Dawood
description: Personal website of Huzeifa Dawood
baseurl: ""
# the subpath of your site, e.g. /blog/
url: "http://huzeifa.github.io" # the base hostname & protocol for your site
twitter_username: huzi94
github_username:  huzeifa
permalink: pretty
# Build settings
markdown: kramdown
